import os

COWBOY_SERVER_PORT = "8000"
COWBOY_INTERNAL_ADDRESS = f"0.0.0.0:{COWBOY_SERVER_PORT}"
COWBOY_SERVER_MAX_THREADS = 5
COWBOY_SERVICE_NAME = "CowboyService"

MAX_GIVE_DAMAGE_RETRIES = 5

class CowboyStatusCodes:
    THIS_SHOT_KILLED_ME_SUCCESS_CODE = "THIS_SHOT_KILLED_ME"
    SUCCESS_CODE = "SUCCESS"
    NO_TARGETS_AVAILABLE_CODE = "NO_TARGETS_AVAILABLE"
    I_AM_DEAD_CODE = "I_AM_DEAD"
    TARGET_IS_DEAD_CODE = "TARGET_IS_DEAD"
    SHOT_FAILED_CODE = "SHOT_FAILED"

GIVE_DAMAGE_SCHEDULED_DELAY_IN_SECONDS = 1.0

WORKING_DIR_PATH = "."
SHARED_VOLUME = os.path.join(WORKING_DIR_PATH, "containers_data")
SHOOTOUT_IN_PROGRESS_FILE_PATH = os.path.join(SHARED_VOLUME, "shootout-in-progress")
COWBOYS_FILE_PATH = os.path.join(WORKING_DIR_PATH, "cowboys.json")

SERVICE_DISCOVERY_SERVER_MAX_THREADS = 5
SERVICE_DISCOVERY_SERVER_PORT = "8001"
SERVICE_DISCOVERY_CONTAINER_NAME = "task_service-discovery_1"
SERVICE_DISCOVERY_INTERNAL_ADDRESS = f"{SERVICE_DISCOVERY_CONTAINER_NAME}:{SERVICE_DISCOVERY_SERVER_PORT}"
SERVICE_DISCOVERY_EXTERNAL_ADDRESS = f"0.0.0.0:{SERVICE_DISCOVERY_SERVER_PORT}"

REPORTING_DELAY_IN_SECONDS = 3
